### PR TITLE
Add GitHub CI configuration

### LINKED ISSUE #3: Add travis CI

### PR DESCRIPTION
**Pull request by berkus**
Closes #3

### CODE REVIEW

**Comment by berkus** [comment]
You'd probably need to enable GitHub Actions for this repository:
image before it runs anything.

See https://github.com/berkus/cortex-a/pull/1 for an example run.

**Comment by andre-richter** [comment]
Thanks!

Please bear with me for ~1.5 weeks, I will address all your PRs then.
Currently no access to a workststion and only shitty mobile internet.

**Comment by berkus** [comment]
Sure, i’m using a magnificent cargo feature to point at a working branch for the time being :)

**Comment by berkus** [comment]
Btw did you enable PR/commit builds?

**Comment by andre-richter** [comment]
I guess so, why?

**Comment by berkus** [comment]
Just didn't see any builds, but cool, if it's running then all is good.


Edit: yeah, I see the builds in Actions  tab now, great.

**Pull request merged**
