### PR TITLE
Update tock-registers dependency to 0.8

### PR DESCRIPTION
**Pull request by berkus**
Update for the new version of tock-registers.

### CODE REVIEW

**Comment by andre-richter** [comment]
Lazy question from my side: Will it break anything?

**Comment by berkus** [comment]
Does not seem so, the only breaking change touches try_from -> try_from_value and that is not used in cortex-a.

Can't really test on my OS, because cortex-a dependency on 0.7 breaks the build so far (too lazy to do manual overrides, don't ask).

**Comment by andre-richter** [comment]
I am currently pondering if this justifies a new major release of `cortex-a`, [since the user is encouraged to bump the tock-registers dependency of the user's project in tandem](https://github.com/rust-embedded/cortex-a#usage), and it contains a breaking change.

**Comment by berkus** [comment]
I believe it does, semver and all that...

**Comment by andre-richter** [comment]
I am seeing some issues with the 0.8 tock version when trying this out locally (https://github.com/tock/tock/issues/3228). Please give me some time to dig around before we indirectly force people to switch to it due to cortex-a.

**Comment by berkus** [comment]
@andre-richter alright, I will get to testing it more with my code this week as well.

**Comment by andre-richter** [comment]
Let’s go directly to 0.8.1, so pending https://github.com/tock/tock/pull/3242.

Since it will be a breaking change due to the tock upgrade anyways, I’ll take the opportunity to also include https://github.com/rust-embedded/cortex-a/commit/9421f40fa2ec02fecc971fb315ca39bcbf95840a. This has been bugging me for some time now.

**Comment by berkus** [comment]
👍🏼

**Comment by berkus** [comment]
Well, my code [here](https://github.com/metta-systems/vesper/blob/9ac097c3cfb276096fa3584c98a07dfebc1f4f00/machine/src/platform/rpi3/gpio.rs#L38) broke because of https://github.com/tock/tock/pull/3088 - making this a major release was a good call.

Error is
```
     |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the evaluated program panicked at 'Invalid size for struct RegisterBlock (expected 244, actual struct size differs)', machine/src/platform/rpi3/gpio.rs:33:1
     |
    ::: /Users/berkus/.cargo/registry/src/github.com-1ecc6299db9ec823/tock-registers-0.8.1/src/macros.rs:165:1
```

So it's conveniently reports what I already know (the address of @END marker, but doesn't tell what it should be, in its opinion). Should be easy to fix.

**Pull request merged**
