### PR TITLE
Add several more registers and fields I've used in debugging my kernel

### PR DESCRIPTION
**Pull request by berkus**
Minor cleanups along the way.

Question - should SPSR_EL3 et al be actually marked as u32 registers? They are u64 in ARMv8ARM.

### CODE REVIEW

**Comment by andre-richter** [comment]
Thanks for all the PRs. Really appreciated!

Give me a couple of days before I can integrate them, since I am currently short on time.

**Comment by andre-richter** [comment]
> Question - should SPSR_EL3 et al be actually marked as u32 registers? They are u64 in ARMv8ARM.

Sounds like a bug. The length should match the ARM ARM.

**Comment by berkus** [comment]
> > Question - should SPSR_EL3 et al be actually marked as u32 registers? They are u64 in ARMv8ARM.
> 
> Sounds like a bug. The length should match the ARM ARM.

Ok, I will update this itmt.

**Comment by berkus** [comment]
@andre-richter updated it!

**Pull request merged**
